import MediatorUser from "./MediatorUser";
import Server from "./Server";
import type { IncomingMessage, ServerResponse } from "node:http";
import type { Server as SocketIOServer } from "socket.io";
import type { Server as SocketIOServerV2 } from "socket.io-v2";
import type { Server as WebSocketServer } from "ws";
import type { tLogger, tEventMap, iEventsMinimal } from "./DescriptorUser";
export interface iOrchestratorOptions {
    "externalResourcesDirectory": string;
    "packageFile": string;
    "descriptorFile": string;
    "mediatorFile": string;
    "serverFile": string;
    "logger"?: tLogger;
}
export default class Orchestrator<T extends iEventsMinimal & tEventMap<T> = iEventsMinimal> extends MediatorUser<T> {
    protected _Server: Server | null;
    protected _socketServer: WebSocketServer | SocketIOServer | SocketIOServerV2 | null;
    protected _checkParameters: boolean;
    protected _checkResponse: boolean;
    protected _packageFile: string;
    protected _descriptorFile: string;
    protected _mediatorFile: string;
    protected _serverFile: string;
    protected _extended: string[];
    enabled: boolean;
    authors: string[];
    description: string;
    dependencies: object | null;
    devDependencies: object | null;
    engines: object | null;
    license: string;
    main: string;
    name: string;
    scripts: object | null;
    version: string;
    constructor(options: iOrchestratorOptions);
    checkConf(): Promise<void>;
    isEnable(): Promise<void>;
    checkFiles(): Promise<void>;
    checkServer(): Promise<void>;
    disableCheckParameters(): this;
    enableCheckParameters(): this;
    disableCheckResponse(): this;
    enableCheckResponse(): this;
    disableCors(): this;
    enableCors(): this;
    appMiddleware(req: IncomingMessage, res: ServerResponse, next: () => void): void;
    socketMiddleware(server: WebSocketServer | SocketIOServer): void;
    load(...data: unknown[]): Promise<void>;
    destroy(...data: unknown[]): Promise<void>;
    init(...data: unknown[]): Promise<void>;
    release(...data: unknown[]): Promise<void>;
    install(...data: unknown[]): Promise<void>;
    update(...data: unknown[]): Promise<void>;
    uninstall(...data: unknown[]): Promise<void>;
}
